### ISSUE TITLE
Feature Request: Zotfile rename attachments keyboard shortcut

### ISSUE THREAD

**Issue by vancleve** [willsALMANJ/Zutilo#111]
The "Rename attachments" shortcut calls the Zotero function `renameSelectedAttachmentsFromParents`. However, if you have Zotfile installed, the "Rename Attachments" menu item triggers `renameSelectedAttachments` in Zotfile and the attachments are renamed following Zotfile rules.

Could a keyboard shortcut be added for Zotfile `renameSelectedAttachments`?

**Comment by vancleve** [comment]
I can also draft a PR for this based on previous commits that add shortcuts: https://github.com/willsALMANJ/Zutilo/commit/2e36a3c347c6f91ccfbda45f4b4fff3c790535bf

**Comment by willsALMANJ** [comment]
Yes, that would be fine to add. The commit you reference is a good model if you want to try adding the feature yourself.

**Comment by vancleve** [comment]
PR created: https://github.com/willsALMANJ/Zutilo/pull/112

**Comment by willsALMANJ** [comment]
Closed by #112

**Comment by kongdd** [comment]
It seems that the shortcut of zotfile rename still not work

**Comment by vancleve** [comment]
It works for me.

This is the shortcut assignment under Zutilo preferenes.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/1442334/199082804-c19ac8b0-4648-455f-8cdd-184144097928.png">

**Comment by kongdd** [comment]
Yes, it is. Thank you.
