### ISSUE TITLE
"Add tag" shortcut not working

### ISSUE THREAD

**Issue by qqobb** [willsALMANJ/Zutilo#113]
After updating to Zotero 5.0.78, the shortcut "Item pane: Add tag" is just like "Item pane: Focus Tags tab". Previously, "Item pane: Add tag" had the same effect as pressing the "Add" button in the "Tags" tab.

It would be great if the old behavior could be restored. It was very useful for quickly tagging items. Thanks a lot for your great add-on!

**Comment by willsALMANJ** [comment]
Yes, that is one of my favorite features as well. I am not sure when I will have time, but I will look into it when I can (if anyone else wants to look at it, feel free).

**Comment by qqobb** [comment]
I tried to track down the error.

Zotero's "Debug Output Logging" is showing a "tagPane is null" error message:

**[JavaScript Error: "TypeError: tagPane is null" {file: "chrome://zutilo/content/zoteroOverlay.js" line: 101}]**
<code>
addTagGUI@chrome://zutilo/content/zoteroOverlay.js:101:1
keys.shortcuts.addTag@chrome://zutilo/content/keys.js:186:5
createKey/<@chrome://zutilo/content/zoteroOverlay.js:1157:17
</code>

The relevant Zutilo code in 'zoteroOverlay.js' that produces this error is <a href="https://github.com/willsALMANJ/Zutilo/blob/df9a2fa9ca59523b7cb5937acebdebd2d3a94a19/addon/chrome/content/zutilo/zoteroOverlay.js#L98">here</a>.

This error seems to result from the "Reactify item tags box" changes, see <a href="https://github.com/zotero/zotero/commit/5791ffeb16f5b15748ba908422b6cf4bd6c0e7e6#diff-31dd5f64dd1753d8dae541f11ef7482b">here</a>.

I suspect that one needs to call the function 'handleAddTag' in 'tagsBox.jsx' somehow, but I don't know how to do it. The function is <a href="https://github.com/zotero/zotero/blob/98a0699f8556545687891966e4122723a292ca87/chrome/content/zotero/components/itemPane/tagsBox.jsx#L73">here</a>.

Maybe @dstillman could help us and check whether there is a quick fix.

**Comment by qqobb** [comment]
It seems that one needs to replace <code>getElementById('zotero-editpane-tags')</code> by <code>querySelector('.tags-box')</code> in 'zoteroOverlay.js', see [here](https://github.com/zotero/zotero/commit/5791ffeb16f5b15748ba908422b6cf4bd6c0e7e6#diff-4bf28e99197f93a1ce6b183970d6d327).

**Comment by willsALMANJ** [comment]
Thanks @qqobb for doing the research. It should be easy to make the fix with this information.

**Comment by willsALMANJ** [comment]
I forgot to tag this issue in the commit message, but this should be closed by 6242643e4dbca050a38497eff29bc83a379de533.

It was a little more complicated than just switching out the query functions, but I put something in that works for now...(had to query for the anonymous "Add" child button of the header and `click()` it because the add new tag function was no longer public).

**Comment by qqobb** [comment]
Great, thanks a lot! The update works like a charm.
