### ISSUE TITLE
Erratic behavior of "modify attachment paths" for (large?) libraries

### ISSUE THREAD

**Issue by Guillaume-Garrigos** [willsALMANJ/Zutilo#115]
Hi,

First of all thanks for your plugin!

I recently moved my database from some folder in C: to some other folder in D: (I'm using Windows 10), and Zotero has some issues dealing with those relative paths, so I installed your plugin to manually force Zotero to understand where are my files now.

If I use the function "modify attachment paths" on one single document, it works like a charm. If I take a couple of documents as well. But if I run it on my entire library (nearly 1300 documents) it does nothing.

So I thought there were some maximal number of documents I could change at a time. So I did some tests, trying to "modify attachment paths" on small subsets and see if it fails for a certain group size.

Actually it behaves quite randomly: I could perfectly use the function on 130 documents, then it failed to do so on 20, then succeeded on 30, ...

Any idea of what is going on?

[Quick update:] Actually it seems that the issue is that there is a *total* amount of documents for which i can change the attachment path! After reapeting this process (on 592 documents) I can no more modify the attachment, even on single documents.

Thanks
Guillaume

**Comment by willsALMANJ** [comment]
Hmm, strange. What about changing back one of the ones you already changed? Maybe there is something different about the remaining ones that don't change. Can you check if anything is printed to the error console when you try to change a document that doesn't change? (Tools->Developer->Error console).

**Comment by Guillaume-Garrigos** [comment]
1) If I try to modify a new document, nothing happens, and the error console says nothing
2) If I try to change back a previously modify document, it does nothing (I still can open it while it shouldn't), and the error console says : (sorry it seems I cannot copy/paste those errors)

![error](https://user-images.githubusercontent.com/19683079/70337660-d7c75480-184b-11ea-9877-43219c7d6e16.png)

**Comment by Guillaume-Garrigos** [comment]
This is certainly useless, but just in case it may helps, here are more details about what I am doing : I moved my documents folder from 
`C:\Users\Guillaume\Documents\OwnCloud\Articles\`
to
`D:\OwnCloud\Articles\`
and I told zotero to use relative paths from D:\OwnCloud\Articles , but it doesn't get the change.

With the function "see attachment paths", I see that my documents are considered to be at:
`C:\Users\Guillaume\Documents\OwnCloud\Articles\title_of_my_document.pdf`
So I use the function "modify attachment paths", where in the first window I give the previous folder:
`C:\Users\Guillaume\Documents\OwnCloud\Articles\` (I leave the box unchecked) 
and in the second window I give 
`D:\OwnCloud\Articles\`
After that, it successfully turned the attachment path of 592 documents to:
`attachments:title_of_my_document.pdf`

**Comment by Guillaume-Garrigos** [comment]
ok, i think I foud the issue : some of my files were not correctly named (the name of the document in the original folder was not following the "name rule" I set up with zotfile) so I guess there were some inconsistency here.

If I skip those files, it goes smoothly. The only issue is that I have many such files and I have no way to find them except when the function fails to convert the paths...

It would be nice if, when modifying the attachment paths of many files, not the entire modification gets cancelled because a single/few documents are problematic.

**Comment by willsALMANJ** [comment]
Oh, yes, I see the bug. It makes sense now. In the `_modifyAttachments` function, `newFullPath` gets initialized as `undefined`. Then, if the `oldFullPath` for a selected attachment starts with the `oldPath` that you entered, `newFullPath` gets set to the `oldFullPath` with the beginning path substituted as desired. However, if the beginning of `oldFullPath` does not match, `newFullPath` is not modified. This is why you saw the bug about the `.attachmentPath` not being a string.

I am concerned though that there is a more serious consequence than the not a string crash. If the first attachment did have a path matching the old path prefix you gave, then `newFullPath` would get set to a string value. Then if a later attachment had a path that did not match the pattern, `newFullPath` would not be updated for it and the old value for `newFullPath` would be used. Do the attachments that did not get changed correctly still have the old paths or did they get changed to have random new paths of other attachments?

**Comment by willsALMANJ** [comment]
I pushed a change (in release 3.3.2) that should address the bug so I closed the issue, but please let me know about the state of your attachments for the non-matching paths.

**Comment by Guillaume-Garrigos** [comment]
So:
1) For a document which is "problematic" in the sense I described above : if I try to change the path, the path becomes `storage:nonmatching_name_file.pdf` . I would have expected `attachment:nonmatching_name.pdf`?
2) For a document that I try to modify together with a problematic document, after changing the path, the path remains set as the old path, in my case `C:\Users\Guillaume\Documents\OwnCloud\Articles\document_name.pdf`

I will now apply your update and see if it changes anything.

**Comment by Guillaume-Garrigos** [comment]
Great, it works perfectly as expected now: I could change all the paths at once, and the command just ignored the few problematic documents I had 👍 

Thank you!

**Comment by willsALMANJ** [comment]
Great!

1. If the attachment is prefixed by `storage:`, that means that the attachment is stored in Zotero's internal storage. When you manage an attachment with ZotFile, it converts the attachment into a linked file attachment -- moving the file out of Zotero's internal storage directoy and changing the attachment path to the path where the attachment was moved. For linked file attachments, there is no `attachment:` prefix.

2. I think this will depend on the order that the attachments are processed in. If you had a non-matching linked file attachment after a matching one, then it would get the path of the matching one as well. If the non-matching one is first, it will crash the function right away and the matching path is never processed. However, in your case, it seems like the problematic items were imported attachments and not linked file attachments with different paths. Imported attachments probably just caused the function to crash any way even if a previous path had matched.

So I think we are lucky that your problematic attachments were imported attachments. If they had been linked file attachments with different paths, those paths could have been overwritten.
