### ISSUE TITLE
create for look up using google scholar engine

### ISSUE THREAD

**Issue by fredericky123** [willsALMANJ/Zutilo#117]
Could you please add this shortcut so that we can easily loop up pdfs using lookup engine, such as google scholar?

**Comment by willsALMANJ** [comment]
This seems easy to add. Just need to look up the name of the function Zotero calls to run the look up engine.

**Comment by fredericky123** [comment]
Thanks! Looking forward to this function.

**Comment by fredericky123** [comment]
when this function will be added?

**Comment by willsALMANJ** [comment]
I'm not sure. I don't have a lot of time to look into it. I will look into when I have a chance if no one else does so first. The first thing is to find the place in the code where Zotero triggers the lookup engine.
