### ISSUE TITLE
Shortcut calling Zotero.BetterBibTeX.ZoteroPane.toTeXstudio()

### ISSUE THREAD

**Issue by dbitouze** [willsALMANJ/Zutilo#119]
I would be nice for Zutilo to provide a shortcut for the "Push references to TeXstudio"  BetterBibTeX's (contextual) menu entry.

[According to its developer @retorquere](https://github.com/retorquere/zotero-better-bibtex/issues/1371#issuecomment-569454366), it should enough for Zutilo to:

- test for the presence of `Zotero.BetterBibTeX` (to know that BBT is installed),
- then call `Zotero.BetterBibTeX.ZoteroPane.toTeXstudio()`.

Many thanks for your attention.

**Comment by willsALMANJ** [comment]
This will be very easy to add to [this section](https://github.com/willsALMANJ/Zutilo/blob/936ea056b349e0b5783ae174d01df1fa985d1368/addon/chrome/content/zutilo/keys.js#L384). It is just a question of finding a little time to add it.

**Comment by willsALMANJ** [comment]
Can you test #120 and see if it does what you want?

**Comment by dbitouze** [comment]
@willsALMANJ I'm sorry but I don't know how to test from a pull request. Could you provide a test release `.xpi` file (this, I know how to install it :smile:).

**Comment by willsALMANJ** [comment]
@dbitouze There is an xpi file linked from the pull request. Let me know if there is a problem with it.

**Comment by dbitouze** [comment]
> @dbitouze There is an xpi file linked from the pull request. Let me know if there is a problem with it.

Sigh, sorry, didn't notice it.

I succeeded to install it and now there's a "Push references to TeXstudio" item in Tools → Zutilo Preferences → Shortcuts. Assigning a shortcut to it didn't work at a first glance but now, after restarting Zotero, works like a charm: many, many thanks!
