### ISSUE TITLE
Zutilo shortcut for "Retrieve metadata for PDF" isn't triggering the action

### ISSUE THREAD

**Issue by small-fork** [willsALMANJ/Zutilo#139]
Hello,

I'm creating a new issue as I've been able to resolve the [original issue](https://github.com/willsALMANJ/Zutilo/issues/137), but am finding the intended action of the Zutilo shortcut is not actioning.

The shortcut for "Retrieve metadata for PDF" isn't triggering the action. To see if it had something to do with overlapping shortcuts, I took a shortcut that is working for another action and assigned it to "Retrieve metadata for PDF" (removed it from the other action), but still no luck with the metadata retrieval triggering.

Nothing pops up (like normally when using the Zotero context menu and selecting "Retrieve metadata for PDF"). I can't tell if the shortcut is doing anything. If I select the action from the normal Zotero context menu, it does trigger the metadata window.

Please let me know if there is any additional information I can provide.

This is the about:config showing a shortcut is assigned:
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/27249070/80146463-80feb500-8577-11ea-9706-55adc2ec886c.png">

**Comment by willsALMANJ** [comment]
c25f0430874398cbdafd454cd920360065ebe7ab should fix this. The API for this function changed in Zotero 5.0.36 over two years ago -- I guess this shortcut is not that popular with Zutilo users.

**Comment by small-fork** [comment]
Apologies @willsALMANJ - I'm not quite sure what I do with the linked file? Thank you!

**Comment by willsALMANJ** [comment]
That is the commit where I fixed this issue. That commit is on the master branch now. I have not yet had time to create a new release of Zutilo that includes this change. If you don't want to build Zutilo from the master branch yourself, you can try using the following link where I just uploaded a version built from the master branch: https://0x0.st/ieeV.xpi

**Comment by small-fork** [comment]
Sorry, @willsALMANJ I'm not familiar with how this works. If I install in Zotero from that file, will it overwrite my current Zutilo settings and keybindings? Thank you again!

**Comment by willsALMANJ** [comment]
Well, just to respond any way -- installing that XPI is just like getting an automatic update when there is a new release. So all the settings are preserved like normal (as long as the update doesn't introduce some change to the way the settings are stored and do some migration). That XPI uses the same update URL as the normal release so once an official release comes out it will update back onto a released version.
