### ISSUE TITLE
Unable to clear item fields

### ISSUE THREAD

**Issue by joelnitta** [willsALMANJ/Zutilo#141]
Thanks for the helpful plugin! 

I am trying to do something along the lines of "Copy + edit + Paste-all: Clearing certain item fields in a large number of records" in the [Usage notes](https://github.com/willsALMANJ/Zutilo/blob/master/docs/USAGE.md). I am able to copy the fields from a blank item as JSON using "copy item fields" as described. 

However, I cannot paste only the blank item field of my choice. I want to clear the URL field (there are a bunch with incorrect URLS that got inserted by Papers in a previous version of my reference database before I ported it over to Zotero).

After copying the JSON fields, I can edit them down to a smaller number that do work with "paste all item fields", e.g.:

```
{
  "itemType": "journalArticle",
  "creators": [],
  "title": "",
  "abstractNote": "",
  "date": "",
  "url": "",
  "accessDate": ""
}
```

This removes the URL, but also those other fields, which I don't want (of course).

However, if I edit the JSON fields just down to URL, like this:

```
{
  "url": ""
}
```

Now the "paste all item fields" function no longer shows up in the Zutilo menu.

For that matter, another smaller set of fields, e.g.,

```
{
  "date": "",
  "url": "",
  "accessDate": ""
}
```

Also does not work.

Is there any way to just clear one field?

MacOS Catalina 10.15.4
Zotero 5.0.85
Zutilo 3.4.0

**Comment by qqobb** [comment]
> Is there any way to just clear one field?

Yes, that should be possible. For example, copy `{"itemType": "book", "url": ""}` to the clipboard and use Zutilo's "paste all item fields". This should clear the URL fields in the selected items. The value for the itemType is irrelevant and will not be used when pasting. Zutilo requires a dummy itemType entry to recognize the clipboard content as something it can paste. See also [this discussion](https://forums.zotero.org/discussion/comment/352056/#Comment_352056) on the Zotero forum.

A consequence of the above is that you can't change the itemType with these Zutilo functions. If you need to do that, use the JavaScript API as explained [here](https://forums.zotero.org/discussion/78245/i-need-javascript-code-to-change-a-lot-items-type) on the Zotero forum.

**Comment by joelnitta** [comment]
That worked, thanks! I knew it was probably one of the fields in addition to URL, but I didn't want to search through them all by trial and error...

**Comment by willsALMANJ** [comment]
Thanks for the information, @qqobb! I created #142 as a follow up to add some of what you wrote to the documentation for paste all item fields.
