### ISSUE TITLE
Fix german translation of docs

### ISSUE THREAD

**Issue by acsr** [willsALMANJ/Zutilo#22]
This is just a reminder to fix the german translation of the docs, I (or someone) needs to finish at:

https://github.com/willsALMANJ/Zutilo/blob/master/chrome/locale/de/zutilo/README.html

todo:

* convert back to markdown without word wraps using pandoc -> document this in #20
* remove word wraps manually if necessary.
* fix the translation from about the middle
* reformat some prose to lists (after the main doc is fixed in english) see #17, #19

**Comment by willsALMANJ** [comment]
Closing in favor of #28 .
