### ISSUE TITLE
Make chapter entries from book entry with one click

### ISSUE THREAD

**Issue by zuphilip** [willsALMANJ/Zutilo#27]
There is a <a href="https://forums.zotero.org/discussion/33902/make-chapter-entries-from-book-entry/">discussion at the zotero forum</a> about a "one-click" option for making a chapter from a book. The current way is a multiple-click workflow: dublicate the book item, change the item type of the book item into book section (and maybe confirm the loose of some information).

A one-click option sounds for me similar to some functionalities you already have implemented in zutilo. Would it be possible to add such a feature?

**Comment by zuphilip** [comment]
ping @willsALMANJ

**Comment by willsALMANJ** [comment]
Sorry, I recovered the files from the dead computer but I haven't had a chance to work on this more yet. I pushed the implementation I had before to another branch. You can see it here: d7517503b6bfd983c08f57c41425bf86d37c2fef. This version does the book author conversion. It does not do the book-item to book conversion that Gracile-fr suggested. Try it out and let me know if it looks good. Note that I didn't propagate the locale strings yet so there will probably be errors if you try to use it with de, es, fr, or zh locales.

**Comment by bwiernik** [comment]
I've used the book section branch a lot. It seems to work well and could be pushed to the main branch.

**Comment by willsALMANJ** [comment]
Thanks, I will try to merge it in soon and release at least a beta xpi on [the releases section](https://github.com/willsALMANJ/Zutilo/releases) and AMO. I still haven't had a chance to review this whole thread carefully and see if there were any requested features that are not in the patch that could be added easily. I know there were some requests directly in conflict with each other but I don't recall if there were some that could be added to the current patch without negatively affecting the way the function works (for some people at least).

**Comment by willsALMANJ** [comment]
I merged the book section creation changes into master with https://github.com/willsALMANJ/Zutilo/commit/534c94e1cc5de5ea41a6b744323c5cb46b996767 and created release 1.2.11pre004 containing the change (https://addons.mozilla.org/en-US/firefox/addon/zutilo-utility-for-zotero/versions/?page=1#version-1.2.11pre004).

The current version changes authors to book authors. I don't work with book sections, so I'm not sure if this is the best implementation or if the author handling should work differently or be configurable, but we can revisit how the authors are handled if someone wants to suggest something (or submit a patch).

**Comment by zuphilip** [comment]
Thank you very much for the implementation!
