### ISSUE TITLE
Does not load for Zotero in separate/app tab or Zotero Standalone.

### ISSUE THREAD

**Issue by wshanks** [willsALMANJ/Zutilo#3]
Currently, Zutilo works fine when Zotero is used as a browser pane in Firefox.  However, when Zotero is set to open in a separate tab or the app tab, Zutilo does not seem to be initialized properly.  The item it adds to Zotero's actions menu (which launches Zutilo's preferences window) is not present and Zotero.Zutilo.init() is not called (a window load eventListener should launch it).  

Some parts of Zutilo are being loaded though because its preferences window can still be accessed via the Addons Manager.  Parts of this window are generated dynamically by methods of Zotero.Zutilo defined in zutilo.js, so it seems like the Zotero.Zutilo object is being created.

The issues are all basically the same with Zotero Standalone, except that it does not populate the preferences window.  This might just be because Zutilo never loads properly and so never creates its preferences.  Then when the functions that populate the preferences window try to access these undefined preferences it crashes.

**Comment by herbie00** [comment]
Hi. Just to tell that the bug "zutilo not showing up on tab mod but showing up on pane mode" could still be there somehow. I've just encountered it. I tried to remove and resinta but it didn't fix it.
I'm using 
- firefox 55.0.3 (64-bit) in a no-install version
- Zotero 4.0.29.22
- Zutilo 2.03

**Comment by willsALMANJ** [comment]
It's probably more accurate to say that the issue came back rather than that it is still there. I can poke at it a little and see if there is an easy fix. I would sasy that I would definitely fix it, but it seems like Zotero 4 is at end of life (there have been no releases for Zotero 4.x since the first release for Zotero 5.x), so it's hard to justify fixing this vs. the other open issues.

**Comment by willsALMANJ** [comment]
Sorry, I couldn't reproduce this. I used

* Firefox 55.0.3 (64-bit)
* Zotero 4.0.29.22
* Zutilo 2.0.3

and the Zutilo menu item showed up for Zotero in a separate tab.
