### ISSUE TITLE
Add shortcut for Open Style Editor

### ISSUE THREAD

**Issue by gracile-fr** [willsALMANJ/Zutilo#41]
Too many clicks to open it at the moment (with Standalone;  with Firefox, you can bookmark csledit.xul).
I wish I'd do it myself but I'm stuck. I tried <code>win.Zotero_Preferences.openInViewer('chrome://zotero/content/tools/csledit.xul', true)</code> without success (undefined).

**Comment by willsALMANJ** [comment]
Hmm, you couldn't get it work in Firefox, or just Standalone? I can take a look at it as well. Debugging issues in Standalone can be difficult because it doesn't have as nice of debugging tools as Firefox.

**Comment by gracile-fr** [comment]
In Firefox…

**Comment by willsALMANJ** [comment]
Ah, okay. `Zotero_Preferences` is not loaded into the main browser context, only into the preferences window context. So calling `openInViewer` is a little bit tricky. One way to do it would be:

    prefs_context = {}
    Services.scriptloader.loadSubScript('chrome://zotero/content/preferences/preferences.js', prefs_context)
    prefs_context.Zotero_Preferences.openInViewer('chrome://zotero/content/tools/csledit.xul', true)

Performance-wise, there might be a better to load the function than `loadSubScript`.

**Comment by gracile-fr** [comment]
This is working if I test it with Execute JS but I got <code>ReferenceError: Zotero is not defined preferences.js:108:0</code> — line 108 has ```if(Zotero.isStandalone)```

**Comment by willsALMANJ** [comment]
Ah, sorry, Zotero needs to be defined as well (`preferences.xul` does this with a `<script>` tag). This should work:

    prefs_context = {}
    Services.scriptloader.loadSubScript('chrome://zotero/content/include.js', prefs_context) 
    Services.scriptloader.loadSubScript('chrome://zotero/content/preferences/preferences.js', prefs_context)
    prefs_context.Zotero_Preferences.openInViewer('chrome://zotero/content/tools/csledit.xul', true)

`include.js` should load `Zotero` into `prefs_context`.

**Comment by willsALMANJ** [comment]
Closed by 095bb92b119de31bcb52618df9ef54bfddd0411a
