### ISSUE TITLE
Incompatibility with Zotero 4.0.28.1

### ISSUE THREAD

**Issue by retorquere** [willsALMANJ/Zutilo#42]
Zutilo 1.2.10.1 (the latest released version from AMO) searches for zotero-status-image-context in line 310 of firefoxOverlay.js, which errors out because it doesn't exist anymore after https://github.com/zotero/zotero/commit/9a87f1595660a1715f3448172d6ce008e308adec#diff-a42cc3f2f595999239df2741cc274f59L71.

**Comment by willsALMANJ** [comment]
I believe this is the same issue as #30 .
