### ISSUE TITLE
Automatic keyword generation

### ISSUE THREAD

**Issue by milara** [willsALMANJ/Zutilo#45]
I can fairly easily generate a Python module that takes a file name and, if it is a PDF, extracts the text, analyzes it, and generates tags to add to the library item. I do not, however, have the expertise to integrate that code into Zutilo or a new Zotero add-on without a steep learning curve.

If this is a reasonable match for Zutilo, and anyone is interested in doing the integrating, please contact me and I'll get to work on the keyword generation.

**Comment by willsALMANJ** [comment]
That sounds like a useful functionality to have. I wonder though if @jlegewie would be interested in integrating it into https://github.com/jlegewie/zotfile? ZotFile already has the ability to extract annotations from PDF's, so it might be a better fit. If not, we can see about fitting it into Zutilo or a new add-on.

**Comment by willsALMANJ** [comment]
By the way, Zotero has some support for full-text indexing of pdfs using tools from Xpdf. I have never looked into this but maybe those could help with interfacing with your module: https://www.zotero.org/support/pdf_fulltext_indexing

**Comment by jlegewie** [comment]
I agree that this sounds like a useful feature. Personally, I am unable to devote a lot of time to zotfile right now but I can still review pull-requests. I guess that doesn't really help milara. There was, however, a plugin that called external python code. I forgot which one it was. If possible, a javascript implementation that relies on zotero's fulltext indexing would be much nicer though. I think Zotero saves the extracted text in a hidden text file in the same folder as the pdf, which could easily be used by a plugin.

**Comment by gracile-fr** [comment]
@jlegewie : <a href="https://github.com/urschrei/pyzotero">pyzotero</a>?

**Comment by jlegewie** [comment]
No, I was thinking about a zotero plugin that calls a python script as an example for milara. [ZoteroQuickLook](https://github.com/mronkko/ZoteroQuickLook) calls a perl script, I think.

**Comment by willsALMANJ** [comment]
Yes, pyzotero would let you interact with Zotero from Python, but @milara wants to interact with Python from the Zotero UI.

I have played around with calling external processes a little bit from Firefox add-ons and it is not too hard to do. I'm not sure what exactly @milara's module will do, but probably all that the add-on needs to do is pass it the location of the pdf and then read back the list of tags to add from it (or something like that, like maybe passing it the pdf text as indexed by Zotero instead of the pdf directly).

**Comment by jlegewie** [comment]
Yes, calling external processes is pretty easy with the code below. I just wasn't sure about cross-platform support of the external executable (the javascript code below should work across platforms). 

```
// path - path to external executable
var cmd = Components.classes["@mozilla.org/file/local;1"].
        createInstance(Components.interfaces.nsIFile);
        file.initWithPath(path);
var proc = Components.classes["@mozilla.org/process/util;1"].
        createInstance(Components.interfaces.nsIProcess);
proc.init(cmd);
// run process
if (!Zotero.isFx36) {
    proc.runw(blocking, args, args.length);
}
else {
    proc.run(blocking, args, args.length);
}
```

**Comment by milara** [comment]
Wow, thanks for the rapid feedback on this idea, guys!

I could have sworn I saw some Python code in the Zutilo repository, but maybe it isn't being used right now?

I'll try to make some time this weekend to throw some code together that works on the Python end, and toss it in a public repository. To start, I'll just implement text-based keyword generation. If the idea gets integrated with a plugin and gains traction, I or others can look into doing things like looking at PDF metadata -- files generated from LaTeX templates may have metadata that indicates keywords or identifies the different sections, for instance, and it would be great to be able to extract things like the ACM keywords from ACM-format papers, and any other formats that have specific keyword ontologies.

**Comment by willsALMANJ** [comment]
Looking forward to seeing what you make.

The Python code in the Zutilo repository is used in the build process for manipulating the localized string files (e.g. the help file is stored in markdown and then converted to html with pandoc; addons.mozilla.org only allows a subset of html on the add-on listing page, so one Python script strips out the unsupported tags that pandoc generates).
