### ISSUE TITLE
 Switcher for Quick Copy Format

### ISSUE THREAD

**Issue by gracile-fr** [willsALMANJ/Zutilo#46]
cf. https://github.com/zotero/zotero/issues/466
but in the meantime, could it be possible to add Dan's solution here : https://forums.zotero.org/discussion/35837/switcher-for-quick-copy-format/?Focus=190328#Comment_190328

**Comment by willsALMANJ** [comment]
Hmm, implement that exact code for Chicago style, or something that allows you to set the shortcut for any QuickCopy translator?

**Comment by gracile-fr** [comment]
Yes something that allows to switch between any installed styles/formats. To avoid too much UI work, that could be two hidden prefs that the user would have to set/fill with the correct values.

**Comment by willsALMANJ** [comment]
Hmm, I had thought about doing this a while back but got sidetracked by other things and didn't do it. That discussion is here: https://github.com/willsALMANJ/Zoterodactyl/issues/3

The quick, hacky way to do it would be to make one to three new shortcuts in Zutilo called QuickCopy 1, QuickCopy 2, etc. and then have preferences in about:config that set which translator correponds to QuickCopy 1, QuickCopy 2, etc.

**Comment by willsALMANJ** [comment]
Okay, I added something along these lines in 30c86fa2360f48ee6b733d3ebd25b01417daa9fc

**Comment by gracile-fr** [comment]
Fantastic, thanks!
[note to self: display a non-disruptive window which shows the selected format during three seconds (cf Zotfile message)]
