### ISSUE TITLE
attachment path only showing "storage:name_of_file"

### ISSUE THREAD

**Issue by rdiaz02** [willsALMANJ/Zutilo#48]
I think this is not the intended behavior: when I click on an entry or on its attachment and I request to be shown the attachment path I get something like `storage:name_of_file`. So what is missing is the full directory path. In case it matters, I use a custom data directory location (`~/Zotero-data`) and, from it, the `storage` subdirectory is a link to another place (`~/Zotero-storage`).  I am running Zotero Standalone in Linux.

**Comment by willsALMANJ** [comment]
What do you want to see the full directory paths of attachments stored in Zotero's internal storage for? When I made the "show attachment paths" function my purpose was to use it to help with using the "modify attachment paths" function (which only works on linked file attachments), so you could see the paths before and after to make sure that the paths changed properly. I would think that with attachments stored in Zotero's internal storage that you would not need to show the paths. If you wanted to look up the location of any specific attachment, the "Show file" menu item wiill select the attachment in the file browser.

By the way, internally, Zotero represents each attachment as a javascript object. What the Zutilo function does is show the value of the `attachmentPath` property, which for internal attachments uses the `storage:name_of_file` format. I'm not sure why it doesn't use the format that would fully specify the location like `storage:<parent_item_hash>/<name_of_file>`.

**Comment by rdiaz02** [comment]
Aha, I see. It was my incorrect understanding of the feature and this is intended behavior. Sorry for the noise. Closing the issue now.

What I wanted this for? Yes, the "Show file" brings me to the directory/folder, and opens up whatever is configured to do file exploring, say pcmanfm or nautilus, or whatever. But having a way to just see/copy the path, directly, without going through nautilus/pcmanfm would be convenient sometimes. But then, this is another feature.

**Comment by willsALMANJ** [comment]
Yes, either a function to show full paths or copy full paths to the clipboard could be a potential Zutilo function if it seemed worthwhile. I mainly use Zotero and ZotFile to manage my attachments so I don't interact with the file locations very often and the "Show file" function is usually all I need, but I could see how a function like that could be useful.

**Comment by rdiaz02** [comment]
Having a way to show (and copy to the clipboard) the full paths would definitely be useful for me :smiley: .  Of course, I understand this does not justify it, since it might be an unusual need.

**Comment by willsALMANJ** [comment]
It would be pretty easy to add and I wouldn't mind adding it at some point. Really, the next thing I would like to do though is clean up the UI (issue #28) because Zutilo has a lot of functions now and the UI is kind of cluttered. I'd like to clean that up before adding more to it. I haven't been able to find time to work on that recently though. It is hard to prioritize working more on Zutilo right now because changes to Firefox have been announced which will probably require Zutilo to be heavily refactored though how exactly is not yet clear.

**Comment by rdiaz02** [comment]
Thanks for the comments and the update. Well, adding it I think would be nice, then. But I do understand that cleaning up the UI and dealing with Firefox's change must come first.
