### ISSUE TITLE
Feature request : "Copy select item links" for attachments providing absolute directory paths

### ISSUE THREAD

**Issue by Friedsoap** [willsALMANJ/Zutilo#51]
Hi,

I think Zotero users would benefit from a function similar to "Copy select item links" but which provides the absolute path to an attachment (it could be called, e.g., "Copy select attachment links"). Since there may be several attachments linked to a Zotero item, this function could be triggered by clicking on the attachment that we want to get the address. 

The underlying idea is that I have many files in Zotero that I need to upload, so being able to get the absolute address of the attachments would enable me to paste that information directly into the upload dialog box. Currently, I need to click on "show file" which open the explorer and then get the address for each file.

Thank you very much for developing such application; it really helps!

Best,

Aleix

**Comment by willsALMANJ** [comment]
Okay, sure. This was discussed some in #48. So with the way you are suggesting to use this, you would only copy attachments one at a time? The function could be made to work on more than one attachment, but I am not sure it is useful since things like upload dialog boxes usually only work on one file at a time. I am wondering what the best format for multiple items would be. I think I have seen some file selection dialogs allow multiple files separated by spaces.

**Comment by Friedsoap** [comment]
Hi and thanks for your quick answer.

Yes, it is the same feature requested in #48. 

The issue is, as you mentioned, the capabilities of the 3rd party software dialog box. Some accept more than one attachment at once (e.g. gmail), but many do not (e.g. the mooc software I use).

I guess you can start by implementing this function for one attachment and then improve the feature to select various attachments at once. You could add a customisation option in the preferences that allows the user to select the separator between the absolute paths of the different selected items [e.g. spaces, commas, tabs and semicolons] and, also, whether quotes are required [none, single quotes and double quotes], as different dialog boxes may require different formats. But it may be worthwhile researching whether that is true because if there is only one format, then there is no customisation need.
 
I hope that helps. 

Best,

Aleix
