### ISSUE TITLE
Zutilo Copy Tags Issue

### ISSUE THREAD

**Issue by bphagan** [willsALMANJ/Zutilo#56]
I have Zotero Standalone 4.0.29.10 installed and Zutilo 2.0.1 plugin.

If I select a document in my Zotero Library, right click and select Zutilo -> Copy Tags, I get the following error:

Zutilo: item selection error
Please select at least one regular item or note.

If I select a parent item, the error does not occur.

Can I use Zutilo to copy tags directly on items? 
Most of my Library does not use Parent Item.

Brett

**Comment by willsALMANJ** [comment]
I think when Zutilo was first written that notes and attachments could not have tags or related items, so I put in checks to make sure tag and relation functions only operated on regular items. I just need to remove these checks from the functions that don't need them any more. I should have looked more closely into this back with #14.

So to answer your specific question, no, you can't copy tags with attachments right now, but I will change that when I have time.

**Comment by bphagan** [comment]
Thank you.

I work for a semiconductor company so I use Zotero to manage all the datasheets, app notes, schematics, erratas, etc.

I don’t use any of the citation features since they don’t apply to these docs.

 

There are constant revs of these documents so it would help me copy tags to updated docs.

**Comment by willsALMANJ** [comment]
This should be fixed now. You can download the updated version at https://github.com/willsALMANJ/Zutilo/releases/tag/v2.0.2 if you don't want to wait for Mozilla to approve it for automatic update.

**Comment by bphagan** [comment]
Many thanks for the quick response.

It is working on Standalone Zotero.

 

Brett
