### ISSUE TITLE
Problem recognizing new files in source folder

### ISSUE THREAD

**Issue by Jmuccigr** [willsALMANJ/Zutilo#57]
Occasionally Zotfile won't recognize that a new file has been added to the source folder which I've got set to a custom one, my Downloads folder. If I "touch" the file, then Zotfile will see it.

Zotero standalone 4.0.29.5, Zotfile 4.2.6, OS X 10.9.5

**Comment by willsALMANJ** [comment]
Hmm, I will flag this for @jlegewie but you probably want to open the issue on the ZotFile issue tracker, not the Zutilo one ; )

**Comment by Jmuccigr** [comment]
Oh, boy. That's what I get for multitasking. Thanks.
