### ISSUE TITLE
Zutilo item selection error whenever I tab between fields elsewhere in Firefox

### ISSUE THREAD

**Issue by kgthreee** [willsALMANJ/Zutilo#58]
I installed zutilo yesterday as a Firefox add-on to clean up extraneous automatic tags in Zotero. It was huge help, thank you!

Now, whenever I tab between fields on a web page in Firefox, I get this error:
Zutilo: item selection error
Please select at least one regular item, note, or attachment.

Firefox version: 47.0.1
Zotero: 4.0.29.10

I haven't installed zutilo for zotero standalone.

Thanks!

**Comment by willsALMANJ** [comment]
That is very strange behavior. So you see that any time you hit the tab key? Is it possible that you accidentally set one of the shortcuts in Zutilo's preferences window to be `<Tab>`?
