### ISSUE TITLE
Modify attachment paths feature broken?

### ISSUE THREAD

**Issue by resistor4u** [willsALMANJ/Zutilo#59]
On Zotero standalone for mac (v. 4.0.29.15), Zutilo's "Modify attachment paths" is not working as it has for me in the past. If I've got a file at:
`/Users/New/Box Sync/zotero/Old/Box Sync/zotero/Dinwoodie_1998_Authorizing voices.pdf`
I want to modify (remove) the partial path ".../Old/Box Sync/zotero/" so that the path becomes:
`/Users/New/Box Sync/zotero/Dinwoodie_1998_Authorizing voices.pdf`
But each time I use the "Modify attachment paths," regardless of whether I select "Replace all instances...," it seems to double the path so that it becomes:
`/Users/New/Box Sync/zotero/New/Box Sync/zotero/Dinwoodie_1998_Authorizing voices.pdf`

**Comment by willsALMANJ** [comment]
Hmm, it works for me in Firefox on 4.0.29.16. I don't have a machine running macOS to test that specifically. What are you putting in the text boxes? I tried putting `zotero/Old/Box Sync/zotero` into the first box (with "Replace all instances...." checked) and `zotero` into the second. I also tried putting `zotero/Old/Box Sync/` into the first and nothing into the second. You have to use "Replace all instance...." if you want to replace a string that does start from the beginning of the path.

**Comment by resistor4u** [comment]
Yes, and I think you can close this, because the issue seems to have been working from two different base directories on two different machines, one of which was using an older version of both zotero and zutilo. After much troubleshooting, the feature is indeed working as expected.

**Comment by willsALMANJ** [comment]
Okay, thanks for the follow up, and I'm glad that it is working for you now.
