### ISSUE TITLE
enable copy tags on pdf item (currently: "please select one regular item or notes")

### ISSUE THREAD

**Issue by WiliTest** [willsALMANJ/Zutilo#62]
I am on zotero 5
Thanks!

**Comment by willsALMANJ** [comment]
What version of Zutilo are you using? This sounds the same as #56 which was addressed in version 2.0.2, but maybe I do not understand your specific case.

**Comment by WiliTest** [comment]
Yes you're right, I wasn't using the latest version. Updating also solved the bugs I had with relate items, copy/paste/remove tags and relocate child note. 

Thanks a lot for your answer and your great plugin!
