### ISSUE TITLE
Request: Shortcut for Add Item by Identifer

### ISSUE THREAD

**Issue by bwiernik** [willsALMANJ/Zutilo#65]
I frequently need to copy a DOI from a reference list and then add an item by identifier Zotero. It would be great if there were a keyboard shortcut either to focus the Add by Identifier pane or to run the command using the contents of the clipboard.

**Comment by willsALMANJ** [comment]
I haven't looked into how to do this yet, but it sounds good to me. Bringing up the text box might be cleaner than reading from the clipboard.

**Comment by bwiernik** [comment]
Agreed! Thanks for looking into this!

**Comment by alexander-winkler** [comment]
Sorry to comment on this closed Issue. I was just wondering if the shortcut is available for Firefox as well. A quick search in the code suggests that the feature was added to chrome only (https://github.com/search?q=repo%3Awshanks%2FZutilo%20lookupid&type=code). It'd be hugely useful for visually impaired people to have this shortcut.

**Comment by wshanks** [comment]
@alexander-winkler I think there is some confusion here. Zutilo is a plugin for Zotero, the standalone application. It doesn't work in Chrome or Firefox. Zotero was a Firefox extension before but it stopped supporting that case several years ago.
