### ISSUE TITLE
Zotero URIs should use new format

### ISSUE THREAD

**Issue by bwiernik** [willsALMANJ/Zutilo#73]
https://forums.zotero.org/discussion/69155/zutilo-uri-is-inaccurate-in-firefox-57-zotero-5-zutilo-2-0-3

**Comment by willsALMANJ** [comment]
Thanks for triaging that for me.
I can look into this more later, but [in zoteroOverlay.js](https://github.com/willsALMANJ/Zutilo/blob/master/addon/chrome/content/zutilo/zoteroOverlay.js#L588) Zutilo just calls `Zotero.URI.getItemURI`. Is that function out of date? Hecksher lists that this is for Zotero 5 and the latest version of Zutilo.
/cc @dstillman @fcheslack

**Comment by fcheslack** [comment]
No, I'm pretty sure this is entirely on the Zotero side (client for outdated subdomain, website for not updating redirects). I was just waiting to see if this was actually a recent regression before addressing it.

**Comment by dstillman** [comment]
It's not an outdated subdomain on the client side — that function is just for generating a URI, not a web address. We don't currently have ways of getting web addresses, but you can just replace ZOTERO_CONFIG.BASE_URI with ZOTERO_CONFIG.WWW_BASE_URL in the final string. (Depending on your scope, you may need `Components.utils.import("resource://zotero/config.js");` to bring that in.)
