### ISSUE TITLE
Issue with Shortcuts tab in French i18n 

### ISSUE THREAD

**Issue by gaalcaras** [willsALMANJ/Zutilo#74]
When switching languages (to French) in Zotero preferences, the shortcuts tab appears to contain nothing.

English:
![English](https://user-images.githubusercontent.com/6551953/35231860-2f52134c-ff9a-11e7-97f3-cb0fe7b65e55.png)

French:
![French](https://user-images.githubusercontent.com/6551953/35231859-2f3291b6-ff9a-11e7-95c6-d9052f1b9e00.png)

I'm running ArchLinux, with Zotero 5.0.34 and Zutilo 3.0.2.

**Comment by willsALMANJ** [comment]
This should be fixed in 3.0.3 now.

**Comment by gaalcaras** [comment]
It works! Thanks a lot 👍
