### ISSUE TITLE
"attach new file" shortcup 

### ISSUE THREAD

**Issue by fredericky123** [willsALMANJ/Zutilo#84]
![image](https://user-images.githubusercontent.com/13982749/38594928-7339e912-3d7b-11e8-8136-47a637e27f57.png)
so that move and attach last file easily

**Comment by willsALMANJ** [comment]
That would be ZotFile specific, but there are already some shortcuts that are BetterBibTeX specific, so that would be fine.

**Comment by fredericky123** [comment]
Oh, yeah, it was Zotfile spefic, but Zotfile specific is different from BBT specific, which is convenient for Latex.
So if this shortcut can be considered will be quite nice!
Thank you!
