### ISSUE TITLE
Enhancement: Copy select collection links

### ISSUE THREAD

**Issue by zuphilip** [willsALMANJ/Zutilo#91]
The `zotero://select` protocols in Zotero now also supports collections, see https://github.com/zotero/zotero/commit/1e3608e82ea88f14589b7c7920472c655c3c9ae2 and https://forums.zotero.org/discussion/73893/zotero-select-for-collections . It was asked in that thread to implement support in the Zutilo menu(s) and I also think this could be useful.

**Comment by bjohas** [comment]
@willsALMANJ - would you accept a PR on this? Specifically,
* Generating “zotero://” links from collections.
* Generating “https://zotero.org/…” links from collections. 

Let me know!

**Comment by willsALMANJ** [comment]
Yes, that would be great!

**Comment by bjohas** [comment]
@retorquere - I've linked this issue from this card: https://github.com/retorquere/zotero-edtechhub/projects/1#card-24367058

**Comment by retorquere** [comment]
Does Zutilo already add things to the collection context menu like it does for items?

**Comment by willsALMANJ** [comment]
So far, Zutilo does not add anything to the collection context menu.

**Comment by willsALMANJ** [comment]
Closed by #103
