### ISSUE TITLE
Strange interval when use Chinese

### ISSUE THREAD

**Issue by specter119** [willsALMANJ/Zutilo#96]
It happens on Linux and Windows for me.

![Screenshot_20190329_235747](https://user-images.githubusercontent.com/8768524/55246784-e7d07280-5280-11e9-930d-b20be5f2b632.png)
![批注 2019-03-30 003129](https://user-images.githubusercontent.com/8768524/55247897-b4dbae00-5283-11e9-953a-e84fa5167b2b.png)

**Comment by willsALMANJ** [comment]
Sorry, can you describe the problem more? I am not seeing what is wrong in the pictures.

**Comment by specter119** [comment]
@willsALMANJ  Sorry, my bad. There's a large interval over the text "常规"(general), "用户界面"(User Interface ). It only happens when the interface language is Chinese.

**Comment by willsALMANJ** [comment]
I see that interval for English as well (unless I misunderstand what you are referring to). Can you post what you see for English?

**Comment by specter119** [comment]
@willsALMANJ Sorry, the interval seems always exists when I set the language to English. However, it looks a little strange right now.

![zutilo_arch_cn](https://user-images.githubusercontent.com/8768524/56416868-c0d7f000-62c4-11e9-822f-03c8c5cff95a.png)
![zutilo_arch_en](https://user-images.githubusercontent.com/8768524/56416870-c0d7f000-62c4-11e9-88dd-c731518a9ec3.png)
![zutilo_win_cn](https://user-images.githubusercontent.com/8768524/56416871-c1708680-62c4-11e9-9af2-691230fb5c6e.png)
![zutilo_win_en](https://user-images.githubusercontent.com/8768524/56416872-c2091d00-62c4-11e9-930c-6a5724433012.png)

**Comment by willsALMANJ** [comment]
I think that space is for showing icons. I based the preferences window on the Zotero one. I am not sure about how to change it to have smaller spaces.
