### ISSUE TITLE
"select item link" seems to be out of date

### ISSUE THREAD

**Issue by bjohas** [willsALMANJ/Zutilo#97]
C.f. https://forums.zotero.org/discussion/78312/zotero-uri-vs-select-item#latest

**Comment by willsALMANJ** [comment]
It seems like this is the recurrence of #63 except now the old format doesn't work any more.

I will look into this when I have time, but you are welcome to fix it first if you like.

**Comment by willsALMANJ** [comment]
I don't have time to test now, but I think this should fix the formatting: https://github.com/willsALMANJ/Zutilo/tree/fix-97

**Comment by bjohas** [comment]
Thank you - that fixes it!

**Comment by willsALMANJ** [comment]
Closed by 2989927c63009b8df31ce800dcf40c2a7db69379
