### ISSUE TITLE
Add shortcuts for actions related to display of tags

### ISSUE THREAD

**Issue by ngirard** [willsALMANJ/Zutilo#99]
Hi,

after adopting an organization scheme based prominently on tags rather than collections, one has to constantly switch on and off the display of automatic tags and local vs global tags ; and the checkboxes triggering these actions are not easily accessible.

It would be very helpful to be able to give shortcuts to them -- I'd even suggest attributing default values for their shortcuts.

The names & labels for these actions are:

- "Show Automatic zotero.tag" / Selector.showAutomatic 
- "Display All Tags in This Library" / zotero.tagSelector.displayAllInLibrary

Thanks in advance !

**Comment by willsALMANJ** [comment]
I'm not sure when I can look at it, but I think these should be easy shortcuts to add.

**Comment by stefanct** [comment]
Deselecting all tags would also be great. This can be found in the same submenu in the tags widget but I did not look at the code.

**Comment by ngirard** [comment]
@willsALMANJ, since you implemented some additional shorcuts very recently, and the matter is still fresh in your mind, would you please consider adding the shorcuts requested in this thread ?

I'm not rushing, I can very well understand your time is limited ; I'm just suggesting it might be the right time now because the cognitive overhead would be minimal.

Cheers!

**Comment by willsALMANJ** [comment]
@ngirard Don't worry -- there is no overhead for me related to the mechanics of adding shortcuts. It is just a matter of finding the time to find and test the appropriate functions and go through the motions of adding them. I think I have somewhat been going in last in first out order with recent feature requests, so these have been sitting for a while. I will try to prioritize them over later ones the next time I have time for Zutilo.

**Comment by willsALMANJ** [comment]
Everything mentioned here should be closed by 7da521e81ab5dccb60105d948335b31d0f297872

**Comment by ngirard** [comment]
@willsALMANJ , thank you very much ! This deserves a release on its own, IMHO. It's a game changer.
